Window:
  Width: 1920
  Height: 1057
---
Viewport:
  Width: 1268
  Height: 914
---
EditorCamera:
  Position: [-1.18499899, -1.93999827, -12.9752283]
  Forward: [0, 0, 1]
  Up: [0, 1, 0]
  Pitch: 0
  Yaw: 0
  Mode: 3D